### ISSUE TITLE
issue with Python 2.7.14 - ModuleNotFoundError

### ISSUE THREAD

**Issue by indera** [aranair/rtscli#1]
Traceback (most recent call last):
  File "/usr/local/bin/rtscli", line 7, in <module>
    from rtscli import cli
  File "/usr/local/lib/python3.6/site-packages/rtscli.py", line 2, in <module>
    from urllib2 import urlopen
ModuleNotFoundError: No module named 'urllib2'

**Comment by aranair** [comment]
You're not using python 2.7. From the error message you can see that it's using python 3.6. You probably want to activate a virtualenv and make sure you're really scoped to python2.7. 

I could make a version for python 3 though; it's not difficult. The urblib2 is deprecated in Python 3.

**Comment by aranair** [comment]
Both should work now... also made some changes cause google finance no longer wants to play nice ): 

(using alphavantage now)
